Repository Unithon-INU/2025_UNITHON_TEAM_5_BE, pull requests merged in 2025-05, with the labels that each got.

#2 [feat/#1] Gemini API 연동 및 응급실 추천 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/curelingo/curelingo/config/RestClientConfig.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorController.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorService.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyAdviceRequest.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyAdviceResponse.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/HospitalCandidate.java
  src/main/java/com/curelingo/curelingo/gemini/GeminiRestClient.java
  src/main/java/com/curelingo/curelingo/gemini/dto/GeminiEmergencyAdvisorPromptRequest.java
  src/main/java/com/curelingo/curelingo/gemini/dto/GeminiEmergencyAdvisorPromptResponse.java
  src/main/java/com/curelingo/curelingo/gemini/prompt/GeminiEmergencyAdvisorPromptBuilder.java
  src/main/java/com/curelingo/curelingo/gemini/service/GeminiEmergencyAdvisorService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#4 [feat/#3] E-Gen API 연동
  build.gradle
  src/main/java/com/curelingo/curelingo/config/RestClientConfig.java
  src/main/java/com/curelingo/curelingo/egen/EgenApiClient.java
  src/main/java/com/curelingo/curelingo/egen/EgenController.java
  src/main/java/com/curelingo/curelingo/egen/EgenMapper.java
  src/main/java/com/curelingo/curelingo/egen/EgenService.java
  src/main/java/com/curelingo/curelingo/egen/model/Body.java
  src/main/java/com/curelingo/curelingo/egen/model/EgenResponse.java
  src/main/java/com/curelingo/curelingo/egen/model/Header.java
  src/main/java/com/curelingo/curelingo/egen/model/Item.java
  src/main/resources/application.properties
Labels: ✨ Feature

#6 [feat/#5] 응급실 추천 기능 수정
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorService.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyAdviceResponse.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/HospitalCandidate.java
  src/main/java/com/curelingo/curelingo/gemini/dto/GeminiEmergencyAdvisorPromptResponse.java
  src/main/java/com/curelingo/curelingo/gemini/prompt/GeminiEmergencyAdvisorPromptBuilder.java
  src/main/java/com/curelingo/curelingo/gemini/service/GeminiEmergencyAdvisorService.java
Labels: ✨ Feature

#8 [set/#7]: Docker 세팅
  .dockerignore
  Dockerfile
  docker-compose.yaml
Labels: ⚙ Setting

#10 Chore/#9
  .gitignore
  Dockerfile
  docker-compose.yaml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: ⚙ Setting, 🌏 Deploy

#13 [feat/#11] E-Gen 응급의료기관 기본정보조회 연결
  src/main/java/com/curelingo/curelingo/egen/EgenApiClient.java
  src/main/java/com/curelingo/curelingo/egen/EgenMapper.java
  src/main/java/com/curelingo/curelingo/egen/basic/HospitalInfoController.java
  src/main/java/com/curelingo/curelingo/egen/basic/HospitalInfoItem.java
  src/main/java/com/curelingo/curelingo/egen/basic/HospitalInfoService.java
  src/main/java/com/curelingo/curelingo/egen/beds/AvailableBedsController.java
  src/main/java/com/curelingo/curelingo/egen/beds/AvailableBedsItem.java
  src/main/java/com/curelingo/curelingo/egen/beds/AvailableBedsService.java
  src/main/java/com/curelingo/curelingo/egen/model/Body.java
  src/main/java/com/curelingo/curelingo/egen/model/EgenResponse.java
Labels: ✨ Feature

#14 [feat/#12] 응급의료기관 위치정보 조회 연결
  src/main/java/com/curelingo/curelingo/egen/nearby/NearbyHospitalController.java
  src/main/java/com/curelingo/curelingo/egen/nearby/NearbyHospitalItem.java
  src/main/java/com/curelingo/curelingo/egen/nearby/NearbyHospitalResponse.java
  src/main/java/com/curelingo/curelingo/egen/nearby/NearbyHospitalService.java
Labels: ✨ Feature
