Repository Unithon-INU/2025_UNITHON_TEAM_5_BE, pull requests merged in 2025-06, with the labels that each got.

#18 [feat/#17] Egen 병/의원별 기본정보 조회
  src/main/java/com/curelingo/curelingo/egen/EgenController.java
  src/main/java/com/curelingo/curelingo/egen/EgenSwagger.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorController.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorSwagger.java
Labels: ✨ Feature, 🔨 Refactor

#20 [feat/#19] E-Gen 병/의원 목록, 위치 정보 조회 연동
  src/main/java/com/curelingo/curelingo/egen/EgenController.java
  src/main/java/com/curelingo/curelingo/egen/EgenService.java
  src/main/java/com/curelingo/curelingo/egen/EgenSwagger.java
  src/main/java/com/curelingo/curelingo/egen/dto/ClinicItem.java
  src/main/java/com/curelingo/curelingo/egen/dto/EgenBody.java
  src/main/java/com/curelingo/curelingo/egen/dto/ItemsWrapperDeserializer.java
  src/main/resources/application.properties
Labels: ✨ Feature

#22 feat: 기본정보조회 서비스 분리
  src/main/java/com/curelingo/curelingo/egen/EgenController.java
  src/main/java/com/curelingo/curelingo/egen/EgenService.java
Labels: ✨ Feature

#27 [Feat/#26] SonarQube
  Dockerfile
  build.gradle
  docker-compose.yaml
Labels: ⚙ Setting, ✨ Feature

#33 [Feat/#32] FullData 기반 전체 병원 정보 MongoDB 저장
  build.gradle
  docker-compose.dev.yaml
  src/main/java/com/curelingo/curelingo/mongodb/Hospital.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalController.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalDto.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalRepository.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalService.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalSwagger.java
  src/main/resources/application.properties
Labels: ✨ Feature

#37 [chore/#36] CI/CD 설정
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
Labels: ⚙ Setting, 🌏 Deploy

#44 [chore/#42] CD 설정 및 certbot 디렉터리 설정
  .github/workflows/cd.yaml
  .gitignore
  certbot/conf/.gitkeep
  certbot/www/.gitkeep
  init-letsencrypt.sh
Labels: ⚙ Setting, 🌏 Deploy

#62 feat: MongoDB 저장 시 병원명, 주소 영문번역
  src/main/java/com/curelingo/curelingo/emergencyhospital/domain/Hospital.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalDto.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalService.java
  src/main/java/com/curelingo/curelingo/mongodb/MongoHospital.java
  src/main/java/com/curelingo/curelingo/translation/TranslationService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#64 [release] Merge develop → main (2025-06-26)
  Dockerfile
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorController.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorService.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorSwagger.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/domain/Hospital.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyAdviceRequest.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyAdviceResponse.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/EmergencyBedStatus.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/dto/HospitalCandidate.java
  src/main/java/com/curelingo/curelingo/gemini/GeminiController.java
  src/main/java/com/curelingo/curelingo/gemini/GeminiSwagger.java
  src/main/java/com/curelingo/curelingo/gemini/chatbot/ChatBotController.java
  src/main/java/com/curelingo/curelingo/gemini/chatbot/ChatBotSwagger.java
  src/main/java/com/curelingo/curelingo/gemini/emergencyadvisor/GeminiEmergencyAdvisorService.java
  src/main/java/com/curelingo/curelingo/gemini/emergencyadvisor/GeminiEmergencyRecommendationResponse.java
  src/main/java/com/curelingo/curelingo/gemini/emergencyadvisor/dto/GeminiEmergencyAdvisorPromptRequest.java
  src/main/java/com/curelingo/curelingo/gemini/emergencyadvisor/dto/GeminiEmergencyAdvisorPromptResponse.java
  src/main/java/com/curelingo/curelingo/gemini/prompt/GeminiEmergencyAdvisorPromptBuilder.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalDto.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalService.java
  src/main/java/com/curelingo/curelingo/mongodb/MongoHospital.java
  src/main/java/com/curelingo/curelingo/translation/TranslationService.java
  src/main/resources/application.properties
Labels: 🌏 Deploy

#66 [Feat/#65] 진료과별 병원 목록 조회, 병원 상세 정보 조회
  src/main/java/com/curelingo/curelingo/clinic/ClinicController.java
  src/main/java/com/curelingo/curelingo/clinic/ClinicService.java
  src/main/java/com/curelingo/curelingo/clinic/ClinicSwagger.java
  src/main/java/com/curelingo/curelingo/clinic/domain/Clinic.java
  src/main/java/com/curelingo/curelingo/clinic/dto/HospitalDetailDto.java
  src/main/java/com/curelingo/curelingo/clinic/dto/NearbyClinicDto.java
  src/main/java/com/curelingo/curelingo/clinic/mapper/ClinicMapper.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalController.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalService.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalSwagger.java
Labels: ✨ Feature

#69 style: 엔드포인트 수정
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorController.java
Labels: 🔨 Refactor

#73 fix: clinic 위도 경도 반환 / 응급실 조회 반경 10키로
  src/main/java/com/curelingo/curelingo/clinic/ClinicService.java
  src/main/java/com/curelingo/curelingo/emergencyhospital/EmergencyAdvisorService.java
Labels: 🔨 Refactor

#75 [Feat/#74] 병원 운영 여부 추가
  src/main/java/com/curelingo/curelingo/clinic/ClinicController.java
  src/main/java/com/curelingo/curelingo/clinic/ClinicService.java
  src/main/java/com/curelingo/curelingo/clinic/ClinicSwagger.java
  src/main/java/com/curelingo/curelingo/clinic/domain/Clinic.java
  src/main/java/com/curelingo/curelingo/clinic/mapper/ClinicMapper.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalController.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalDto.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalService.java
  src/main/java/com/curelingo/curelingo/mongodb/HospitalSwagger.java
Labels: ✨ Feature
